apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsule-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app-deployment 
  template:
    metadata:
      labels:
        app: node-app-deployment
    spec:
      containers:
      - name: myapp
        image: keerthid20/event:latest
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017/eventDB"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {}
