apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  template: 
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: nginx
          name: nginx-cont
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: web