apiVersion: v1
kind: Service
metadata:
  name: node-svc-event
spec:
  selector:
    app: event-org     # Correct selector to match deployment
  ports:
    - protocol: TCP
      port: 80         # External port for LoadBalancer
      targetPort: 3003 # Port inside the container running your app
  type: LoadBalancer
